spring:
  config:
    name: application

  application:
    name: study

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: "sa"
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    cache: false
server:
  port: 8080

# 로깅 설정
logging:
  level:
    com.divary: DEBUG\
